### ISSUE TITLE
confluentcloud_kafka_acl resource not applying principle

### ISSUE THREAD

**Issue by salyateem13** [confluentinc/terraform-provider-confluentcloud#34]
Using provider version 0.3.0

```
resource "confluentcloud_kafka_acl" "describe-basic-cluster" {
  kafka_cluster = var.kafka_cluster_id
  resource_type = "CLUSTER"
  resource_name = "kafka-cluster"
  pattern_type  = "LITERAL"
  principal     = "User:sa-55555"
  host          = "*"
  operation     = "DESCRIBE"
  permission    = "ALLOW"
  http_endpoint = var.kafka_http_endpoint
  credentials {
    key    = var.cluster_api_key
    secret = var.cluster_api_secret
  }
}
```

After applying listing cluster ACL via cli yields. Note that principle field is empty
```
    Principal    | Permission | Operation | ResourceType | ResourceName  | PatternType  
 ------------+------------+-----------+--------------+---------------+--------------
   User:          | ALLOW      | DESCRIBE  | CLUSTER      | kafka-cluster | LITERAL  
```

**Comment by linouk23** [comment]
👋 @salyateem13 thanks for opening an issue!

That's a well known problem that we've been working on and planning to address in our future releases.

At the meantime, instead of passing `sa-55555` you have to manually find its corresponding int ID by following this [guide](https://registry.terraform.io/providers/confluentinc/confluentcloud/latest/docs/guides/sample-project#use-the-confluent-cloud-console-to-inspect-your-resources) and use it instead `principal     = "User:123456"`.

Let me know if that helps!

**Comment by linouk23** [comment]
@salyateem13 starting from `0.4.0` [version](https://github.com/confluentinc/terraform-provider-confluentcloud/blob/master/CHANGELOG.md#040-january-28-2022) TF Provider supports `principal = "User:sa-abc123"` so you don't need to look up corresponding int ID manually and can reference SA's ID:
```
principal     = "User:${confluentcloud_service_account.app-producer.id}"
```
