### ISSUE TITLE
Support for dedicated Kafka cluster

### ISSUE THREAD

**Issue by bluedog13** [confluentinc/terraform-provider-confluentcloud#5]
Currently, I see the support only for basic and standard kafka cluster creation in the confluentcloud_kafka_cluster resource. 

Is there a plan to support creation of "[dedicated](https://docs.confluent.io/cloud/current/clusters/cluster-types.html#dedicated-clusters)" cluster in future releases? 

Thanks.

**Comment by linouk23** [comment]
@bluedog13 @PradhyumnVangala check out our new `0.2.0` version where we [added](https://github.com/confluentinc/terraform-provider-confluentcloud/blob/master/CHANGELOG.md) support for dedicated Kafka clusters lifecycle management on a public network:
![image](https://user-images.githubusercontent.com/5459870/140555939-ac01d628-1cdf-4a19-b0e0-60c7509307cc.png)


In order to use `0.2.0` version please update your `main.tf`:
```
terraform {
  required_providers {
    confluentcloud = {
      source  = "confluentinc/confluentcloud"
      version = "0.2.0"
    }
  }
}
```
and here's a sample config for creating a dedicated cluster:
```
resource "confluentcloud_environment" "test-env" {
  display_name = "test_env"
}

resource "confluentcloud_kafka_cluster" "test-dedicated-cluster" {
  display_name = "test_cluster"
  availability = "SINGLE_ZONE"
  cloud = "GCP"
  region = "us-central1"
  dedicated {
    cku = 1
  }
  environment {
    id = confluentcloud_environment.test-env.id
  }
}
```
