### ISSUE TITLE
confluentcloud_service_account update dispay_name fails

### ISSUE THREAD

**Issue by fprojetto** [confluentinc/terraform-provider-confluentcloud#57]
Changing the `display_name` in a resource of type `confluentcloud_service_account` does not work. 

The provider tries to update the field but the Confluent API does not allow to update the display_name, see [API docs](https://docs.confluent.io/cloud/current/api.html#operation/updateIamV2ServiceAccount).

Proposed solution: change the schema to recreate the service account when the display name is changed, ie. set ForceNew for the  `paramDisplayName` key  https://github.com/confluentinc/terraform-provider-confluentcloud/blob/390dc418dfa6cc9014cdf0448d9e718b26e28019/internal/provider/resource_service_account.go#L48-L53

**Comment by linouk23** [comment]
Thanks for opening the issue @fprojetto and proposing the solution!

We'll add it to our next release 👍

**Comment by linouk23** [comment]
@fprojetto we're very excited to let you know we've just published a new version of TF Provider that includes the fix for this issue among other [very exciting improvements](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.m): it enables fully automated provisioning of our key Kafka workflows (see the [demo](https://asciinema.org/a/491871)) with no more manual intervention and makes it our biggest and most impactful release.

The only gotcha we've renamed it from `confluentinc/confluentcloud` to `confluentinc/confluent` but we published a [migration guide](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/upgrade-guide-0.7.0) so it should be fairly straightforward. The existing `confluentinc/confluentcloud` will be deprecated soon so we'd recommend switching as soon as possible.

New `confluentinc/confluent` provider also includes a lot of sample configurations so you won't need to write them from scratch. You can find them [here](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/sample-project#create-resources-on-confluent-cloud-via-terraform), find a full list of changes [here](https://github.com/confluentinc/terraform-provider-confluent/blob/master/CHANGELOG.md).
